include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    file_names: false
    use_key_in_widget_constructors: false
    prefer_single_quotes: false
    prefer_const_constructors: false
    curly_braces_in_flow_control_structures: false
